[package]
name = "test-equality"
version = "0.1.0"
publish = false
edition = "2024"

[features]
default = ["direct-sum", "linked-cells", "direct-sum-parallel"]
print = ["chrono"]
full = []
extended = ["full"]
quick = []

# algorithms
direct-sum = []
linked-cells = []
direct-sum-parallel = []

[dependencies]
ansi_term = "0.12"
chrono = { version = "0.4", optional = true }
lscpu = "1.0.9"
num_cpus = "1.0"
