//! Defines a XYZ writer for the simulation data, outputting `.xyz` files.

use super::OutputWriter;
use moldyn_core::SimulationTrait;
use std::io::{BufWriter, Write};

/// A simple XYZ writer for the simulation data. This implementation is not
/// used and exists only to match the template code of the legacy C++ codebase.
///
/// # Output Example
///
/// ```text
/// 4
/// Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for file format doku.
/// Ar 0 0 0
/// Ar -0.01 1 0
/// Ar -0.00425 5.36 0
/// Ar 34.75 0.00029600000000000004 0
/// ```
#[derive(Default)]
pub struct XyzWriter {
    pub frame_number: usize,
}

impl OutputWriter for XyzWriter {
    fn next_frame_number(&mut self) -> usize {
        self.frame_number += 1;
        self.frame_number
    }

    fn write_frame(
        &mut self,
        writer: &mut BufWriter<std::fs::File>,
        state: &dyn SimulationTrait,
    ) -> std::io::Result<()> {
        writeln!(writer, "{}", state.particle_count())?;
        writeln!(
            writer,
            "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for file format doku."
        )?;

        for p in state.particles() {
            let position = p.get_position();
            writeln!(writer, "Ar {} {} {}", position.x, position.y, position.z)
                .expect("write error");
        }

        Ok(())
    }

    fn extension(&self) -> &str {
        "xyz"
    }
}
