//! Defines a YAML writer for the simulation data.

use super::OutputWriter;
use moldyn_core::Simulation;
use std::io::{BufWriter, Write};

/// A simple YAML writer for the simulation data.
///
/// # Output Example
///
/// ```yaml
/// # Generated by MolSim.
/// # This output format can be re-inserted into the program. See
/// # https://en.wikipedia.org/wiki/YAML for file format doku.
///
/// name: null
/// force: direct-sum
/// algorithm: newton
///
/// # TODO: write updated args (start time should be offset)
///
/// particles:
/// - position: [0, 0, 0]
///   velocity: [-0.0000000008563553373154629, 0.0000009058561490167886, 0]
///   mass:     1
/// - position: [-0.01, 1, 0]
///   velocity: [-0.9999500035551665, -0.004998404868413561, 0]
///   mass:     0.000003
/// - position: [-0.00425, 5.36, 0]
///   velocity: [-0.42499926034973373, -0.0009328386747764901, 0]
///   mass:     0.000955
/// - position: [34.75, 0.00029600000000000004, 0]
///   velocity: [-0.0001440195248088764, 0.029600019482983273, 0]
///   mass:     0.00000000000001
/// ```
#[derive(Default)]
pub struct YamlWriter {
    pub frame_number: usize,
}

impl OutputWriter for YamlWriter {
    fn next_frame_number(&mut self) -> usize {
        self.frame_number += 1;
        self.frame_number
    }

    fn write_frame(
        &mut self,
        writer: &mut BufWriter<std::fs::File>,
        state: &dyn Simulation,
    ) -> std::io::Result<()> {
        writeln!(
            writer,
            "# Generated by MolSim.
# This output format can be re-inserted into the program. See
# https://en.wikipedia.org/wiki/YAML for file format doku.

name: {}
force: {}
algorithm: {}
            ",
            "null".to_string(),
            state.system_name(),
            state.get_force().system_name(),
        )?;

        writeln!(
            writer,
            "# TODO: write updated args (start time should be offset)\n"
        )?;

        // let result = serde_yaml::to_writer(writer, state);
        // result.map_err(|e| Error::new(ErrorKind::InvalidData, e))

        // the problem was that `impl Serialization for dyn Trait` assumes static lifetime
        // https://stackoverflow.com/a/78637718
        // let parsed =
        //     serde_yaml::to_string(&file).map_err(|e| Error::new(ErrorKind::InvalidData, e))?;
        // writeln!(writer, "{}", parsed)?;

        match state.particle_count() {
            0 => writeln!(writer, "particles: []")?,
            _ => {
                writeln!(writer, "particles:")?;

                for p in state.particles() {
                    writeln!(writer, "- position: {}", p.get_position())?;
                    writeln!(writer, "  velocity: {}", p.get_velocity())?;
                    writeln!(writer, "  mass:     {}", p.get_mass())?;
                }
            }
        }

        Ok(())
    }

    fn extension(&self) -> &str {
        "yml"
    }
}
