//! This module contains the [Particle] struct.
//! 
//! Author: Anatoly Weinstein
//! Created: April 2026

/// A struct representing a particle record in the simulation.
#[derive(Debug, PartialEq)]
pub struct Particle {
    /// Position of the particle in 3D space.
    x: [f64; 3],

    /// Velocity of the particle in 3D space.
    v: [f64; 3],

    /// Force effective on the particle in 3D space.
    f: [f64; 3],

    /// Force which was effective on the particle in the previous time step.
    old_f: [f64; 3],

    /// Mass of the particle.
    m: f64,

    /// Type of the particle (Use it for whatever you want e.g. different matters, "Oxygen", "Hydrogen").
    _type: i32,
}

impl Particle {
    /// Creates a new particle with the given parameters.
    pub fn new(x: [f64; 3], v: [f64; 3], m: f64, _type: i32) -> Self {
        println!("Particle generated!");

        Self {
            x,
            v,
            f: [0.0; 3],
            old_f: [0.0; 3],
            m,
            _type,
        }
    }

    pub fn get_x(&self) -> &[f64; 3] {
        &self.x
    }

    pub fn get_v(&self) -> &[f64; 3] {
        &self.v
    }

    pub fn get_f(&self) -> &[f64; 3] {
        &self.f
    }

    pub fn get_old_f(&self) -> &[f64; 3] {
        &self.old_f
    }

    pub fn get_m(&self) -> f64 {
        self.m
    }

    pub fn get_type(&self) -> i32 {
        self._type
    }
}

impl std::fmt::Display for Particle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Particle X: {:?}, v: {:?}, f: {:?}, old_f: {:?}, m: {}, type: {}",
            self.x, self.v, self.f, self.old_f, self.m, self._type
        )
    }
}

impl std::default::Default for Particle {
    fn default() -> Self {
        println!("Particle generated!");

        Self {
            x: [0.0; 3],
            v: [0.0; 3],
            f: [0.0; 3],
            old_f: [0.0; 3],
            m: 1.0,
            _type: 0,
        }
    }
}

impl std::clone::Clone for Particle {
    fn clone(&self) -> Self {
        println!("Particle generated by copy!");

        Self {
            x: self.x,
            v: self.v,
            f: self.f,
            old_f: self.old_f,
            m: self.m,
            _type: self._type,
        }
    }
}

// read more about rust destructor trait: https://doc.rust-lang.org/std/ops/trait.Drop.html
impl Drop for Particle {
    fn drop(&mut self) {
        println!("Particle destructed!");
    }
}
