/**
 * @file YAMLReader.h
 * @author Anatoly Weinstein
 *
 * @brief
 */

#pragma once

#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>

#include "yaml-cpp/yaml.h"

#include "YAMLImplementation.h"
#include "Writer.h"
#include "container/DirectSum.h"
#include "container/ParticleContainer.h"
#include "force/Newton.h"
#include "Reader.h"
#include "Simulation.h"
#include "Vec3.h"

struct XYZWriter : public Writer
{
public:
    /**
     * @brief Creates a new YAML file writer.
     */
    XYZWriter(const std::filesystem::path file_path, const Simulation<DirectSum> &simulation) : Writer(file_path, simulation) {}

    /**
     * @brief Consume the YAML file and return a Simulation struct.
     *
     * # Note
     *
     * There was a bug previously where the output file could not be parsed by
     * ParaView. Compare the following two outputs.
     *
     * ```
     * 4
     * Generated by MolSim (C++). See http://openbabel.org/wiki/XYZ_(format) for file format doku.Ar 0 0 0
     * Ar -0.0014 1 0
     * Ar -0.000595 5.36 0
     * Ar 34.75 4.144e-05 0
     * ```
     *
     * And Rust:
     *
     * ```
     * 4
     * Generated by MolSim (Rust). See http://openbabel.org/wiki/XYZ_(format) for file format doku.
     * Ar 0 0 0
     * Ar -0.014 1 0
     * Ar -0.0059499999999999996 5.36 0
     * Ar 34.75 0.00041440000000000004 0
     * ```
     */
    void write(const int frame) const override
    {
        std::ofstream output_file(frame_file_path(frame));

        output_file << simulation.size() << "\n";
        output_file << "Generated by MolSim (C++). See http://openbabel.org/wiki/XYZ_(format) for file format doku.\n";

        // https://stackoverflow.com/a/265365
        // ignores scientific notation for floating numbers (breaks paraview)
        output_file << std::fixed;

        simulation.for_each_particles(
            [&output_file](const Particle &particle)
            {
                auto position = particle.get_position();
                output_file << "Ar " << position.x << " " << position.y << " " << position.z << "\n";
            });
    }
};
