//! For writing XYZ files.
//!
//! Author: Anatoly Weinstein
//! Created: April 2026

use crate::output_writer::OutputWriter;
use crate::particle::Particle;
use std::fs::File;
use std::io::{BufWriter, Result, Write};

pub struct XYZWriter;

impl OutputWriter for XYZWriter {
    fn plot_particles(
        &self,
        particles: &mut Vec<Particle>,
        filename: &str,
        iteration: usize,
    ) -> Result<()> {
        let output_filename = format!("{filename}_{iteration:0>4}.xyz");

        let f = File::create(&output_filename)?;
        let mut writer = BufWriter::new(f);

        writeln!(writer, "{}", particles.len())?;
        writeln!(
            writer,
            "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for file format doku."
        )?;

        for p in particles {
            let x = p.get_x();
            writeln!(writer, "Ar {} {} {}", x[0], x[1], x[2])?;
        }

        writer.flush()?;
        Ok(())
    }
}
