# Depends on Cargo Build.
# Tests Rust

name: Cargo Test

# https://stackoverflow.com/a/64733705
on:
  workflow_run:
    workflows: ["Cargo Build"]
    types:
      - completed
env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    uses: ./.github/workflows/cargo.yml

  test:
    name: Test Rust Project
    runs-on: ubuntu-latest
    # https://stackoverflow.com/a/71489231
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [build]
    steps:
      - run: cargo test --verbose
  