name: C++ Build & Test

on:
  push:
    paths:
      - cpp-moldyn-cli/**
      - cpp-moldyn-core/**
      - cpp-moldyn-test/**
  workflow_dispatch:

jobs:
  build_and_test:
    uses: ./.github/workflows/cmake.yml
    with:
      build_dir: target/cpp
      run_build: true
      run_tests: true
      cmake_options: CMAKE_CXX_FLAGS="-fsanitize=address"
